# Configuration file for pre-commit-hooks that will
# run before allowing commits to the repository.
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
...
